---
- hosts: nfs_clients
  remote_user: uansible
  sudo: yes

  tasks:
    - name: Ensure NFS common is installed.
      apt: name=nfs-common state=installed update_cache=yes

    - name: Create mountable dir
      file: path=/jenkins_nfs state=directory mode=777 owner=root group=root

    - name: set mountpoints
      mount: name=/jenkins_nfs src=10.0.0.11:/share fstype=nfs opts=defaults,nobootwait dump=0 passno=2 state=mounted

